config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :follows, :followers
    end
    get "posts_on_date" => "users#posts_on_date"
    resource :relationships, only: [:create, :destroy]
  # 	get "followings" => "relationships#followings", as: "followings"
  # 	get "followers" => "relationships#followers", as: "followers"
  end

  	get "/search", to: "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォローしている関連付け
  # has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされている関連付け
  # has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしているユーザーを取得
  # has_many :followings, through: :relationships, source: :followed
  # フォロワーを取得
  # has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしている関連付け
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされている関連付け
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしているユーザーを取得
  has_many :following_users, through: :followers, source: :followed
  # フォロワーを取得
  has_many :follower_users, through: :followeds, source: :follower
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # 指定したユーザーをフォローする
  # def follow(user)
  # relationships.create(followed_id: user_id)
  # end
  # # 指定したユーザーのフォローを解除する
  # def unfollow(user)
  #   relationships.find_by(followed_id: user_id).destroy
  # end
  # # 指定したユーザーをフォローしているかどうかを判定
  # def following?(user)
  #   followings.include?(user)
  # end
  
  # 指定したユーザーをフォローする
  def follow(user_id)
    followers.create(followed_id: user_id)
  end
  # 指定したユーザーのフォローを解除する
  def unfollow(user_id)
    followers.find_by(followed_id: user_id).destroy
  end
  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    following_users.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.following_users
  end

  def followers
    user = User.find(params[:id])
    @users = user.follower_users
  end

  def posts_on_date
  # @user = User.find(params[:user_id]) ###①
  # @books = @user.books.where(created_at: params[:created_at].to_date.all_day) ###②
  # リクエストの中からユーザーIDを取得し、データベースからユーザー情報を取得
  user = User.includes(:books).find(params[:user_id])
  # リクエストの中から指定された日付を取得し、日付オブジェクトに変換
  date = Date.parse(params[:created_at])
  # ユーザーが指定した日に投稿した本（books）をデータベースから検索
  @books = user.books.where(created_at: date.all_day)
  # 検索結果を表示するためのビュー（posts_on_date_form）にデータを送る
  render :posts_on_date_form
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followers.count %></td>
        <td>フォロワー数: <%= user.followeds.count %></td>
        <td><%= render "relationships/btn", user: user, options: { class: "follow-link" } %></td>
        <td><%= link_to 'Show', user, data: { "turbolinks" => false } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followers.count, follows_user_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followeds.count, followers_user_path(user) %></th>
  </tr>
</table>

<div class="row">
  <% if current_user != user %>
    <td><%= render "relationships/btn", user: user, options: { class: ""} %></td>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/_posts_on_date_form.html.erb
<!-- 検索フォーム部分 -->
<div class="row my-3">
  <div class="col-auto">
    <!-- フォームを生成 -->
    <%= form_with url: user_posts_on_date_path(user), method: :get, local: false do |f| %>
      <!-- 入力フィールドと送信ボタンをグループ化 -->
      <div class="input-group">
        <!-- 日付を選択する入力フィールド -->
        <%= f.date_field :created_at, class: "form-control" %>
        <!-- 送信ボタンを表示 -->
        <div class="input-group-append">
          <%= f.submit "検索", class: "btn btn-info" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- 検索結果を表示するためのコンテナ -->
<div class="posts_on_date_table mb-2">
</div>

app/views/users/_show.html.erb
<h3>投稿数の前日比・前週比</h3>
<div class="table_width">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>今日の投稿</th>
        <th>昨日の投稿</th>
        <th>前日比</th>
      </tr>
    </thead>
    <tbody>
      <tr>
	      <td><%= today_book.count %></td>
	      <td><%= yesterday_book.count %></td>
        <% if yesterday_book.count == 0 %>
          <td>前日の投稿はなし</td>
        <% else %>
          <td><% the_day_before =   today_book.count / yesterday_book.count  %>
          <%= (the_day_before * 100).round %>%</td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>今週の投稿</th>
        <th>先週の投稿</th>
        <th>先週比</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= this_week_book.count %></td>
        <td><%= last_week_book.count %></td>
        <% if last_week_book.count == 0 %>
          <td>先週の投稿はなし</td>
        <% else %>
          <td><% the_week_before = this_week_book.count / last_week_book.count  %>
          <%= (the_week_before * 100).round %>%</td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

<h4>7日間分の投稿数</h4>
<table class='table table-bordered'>
  <thead>
    <tr>
      <th>6日前</th>
      <th>5日前</th>
      <th>4日前</th>
      <th>3日前</th>
      <th>2日前</th>
      <th>1日前</th>
      <th>今日</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= books.created_6day_ago.count %></td>
      <td><%= books.created_5day_ago.count %></td>
       <td><%= books.created_4day_ago.count %></td>
      <td><%= books.created_3day_ago.count %></td>
      <td><%= books.created_2day_ago.count %></td>
      <td><%= books.created_yesterday.count %></td>
      <td><%= books.created_today.count %></td>
    </tr>
  </tbody>
</table>

<canvas id="postCountChart"></canvas>
<script>
  // ページが読み込まれたときの処理
  $(document).on('turbolinks:load', function() {
    // グラフを描画するためのCanvas要素を取得
    var ctx = document.getElementById("postCountChart");

    // Chart.jsを使ってグラフを作成
    var postCountChart = new Chart(ctx, {
      type: 'line', // ラインチャートを使用

      data: {
        // グラフのラベル（x軸の値）
        labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],

        datasets: [
          {
            // データセットのラベル
            label: '投稿した本の数',

            // データセットの値
            data: [
              <%= @books.created_6day_ago.count %>, // 6日前の投稿数
              <%= @books.created_5day_ago.count %>, // 5日前の投稿数
              <%= @books.created_4day_ago.count %>, // 4日前の投稿数
              <%= @books.created_3day_ago.count %>, // 3日前の投稿数
              <%= @books.created_2day_ago.count %>, // 2日前の投稿数
              <%= @books.created_yesterday.count %>, // 昨日の投稿数
              <%= @books.created_today.count %> // 今日の投稿数
            ],

            // グラフの線の色（緑）
            borderColor: "rgba(0, 255, 0, 1)",

            // グラフの背景色（透明）
            backgroundColor: "rgba(0, 0, 0, 0)",

            // グラフの曲線の滑らかさ（0から1の範囲で設定。数値が大きくなるほど曲線が滑らかになる）
            tension: 0.3
          }
        ],
      },

      options: {
        title: {
          // グラフのタイトル表示
          display: true,
          text: '7日間の投稿数の比較'
        },

        responsive: true, // グラフのレスポンシブデザインを有効化

        scales: {
          y: {
            // y軸（縦軸）の設定。設定しないと自動になるので書かなくても良い。
            suggestedMin: 0, // 最小値を0に設定
            suggestedMax: 10 // 最大値を10に設定
          },
        },
      }
    });
  });
</script>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render "/users/index", users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render "users/index", users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/posts_on_date_form.js.erb
$('.posts_on_date_table').html(`
  <h3>検索結果</h3>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
      <%= render 'posts_on_date_form', user: @user %>
      <%= render 'show', today_book: @today_book, yesterday_book: @yesterday_book, the_day_before: @the_day_before, this_week_book: @this_week_book, last_week_book: @last_week_book, the_week_before: @the_week_before, books: @books %>
    </div>
  </div>
</div>